### ISSUE TITLE
QQ群签到机器人

### ISSUE THREAD

**Issue by Jimesarrice** [newbe36524/Newbe.Mahua.Framework.V1#21]
QQ群签到机器人
基于Newbe.Mahua1.17实现
实现了基础的QQ群签到的功能，数据库可以存储每个用户的签到天数，积分，最后签到日期，以此来配合一切其他群管理模块，用户每天可以签到一次，随机获取积分，积分可配合其他功能进行消费，每天对每个已签到用户生成一个近似随机的人品值以供娱乐，签到时间不同对每个用户划分等级，以显示用户活跃程度。
大概就是这些功能，通过二次开发可以扩展很多玩法。

感谢大佬给我们提供了这么优秀的框架，在我学习开发的过程中给与了我很多帮助

Github链接：https://github.com/Jimesarrice/Gemeral_QQSignin_Framework

**Comment by newbe36524** [comment]
@all-contributors please add @Jimesarrice for idea
