### ISSUE TITLE
项目模板无法正常生成

### ISSUE THREAD

**Issue by newbe36524** [newbe36524/Newbe.Mahua.Framework.V1#24]
// 需要填写以下标记为 TODO 的内容

**基本信息**

Mahua 版本 ： 1.18

**详细过程**

使用最新模板创建项目

**如何重现**

重现步骤:

按照教程创建项目，在脚本运行时出现错误

**来点截图**

![image](https://user-images.githubusercontent.com/7685462/74601166-f6f92280-50d5-11ea-9eb2-3674ceb65ef6.png)

**Comment by lv69** [comment]
find it.

**Comment by newbe36524** [comment]
@all-contributors please add @lv69 for bug
